/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.davidbuzatto.basicscreenbroadcast.gui;

import br.com.davidbuzatto.basicscreenbroadcast.gui.model.BroadcastArea;
import java.awt.Color;
import java.awt.GraphicsEnvironment;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.KeyStroke;

/**
 *
 * @author David
 */
public class BroadcastAreaSelectDialog extends javax.swing.JDialog {

    private MainWindow parent;
    private KeyboardFocusManager focusManager;
    private ApplicationKeyEventDispatcher appKeyDisp;
    
    /**
     * Creates new form BroadcastAreaSelectDialog
     */
    public BroadcastAreaSelectDialog( MainWindow parent, boolean modal ) {
        
        super( parent, modal );
        this.parent = parent;
        
        initComponents();
        setBackground( new Color( 0, 0, 0, 50 ) );
        
        setDefaultCloseOperation( DISPOSE_ON_CLOSE );
        setBounds( GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds() );
        
        broadcastAreaSelectPanel.setBroadcastAreaList( parent.getBroadcastAreas(), this );
        
        // ENTER and ESC actions
        getRootPane().getInputMap( JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT ).put( 
                KeyStroke.getKeyStroke( KeyEvent.VK_ESCAPE, 0 ), "CANCEL" );
        getRootPane().getActionMap().put( "CANCEL", new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent e) {
                cancel();
            }
        });
        getRootPane().setDefaultButton( btnOkBL );
        
        /*addKeyEventDispatcher();
        
        addWindowListener( new WindowAdapter() {
            @Override
            public void windowClosed( WindowEvent e ) {
                removeKeyEventDispatcher();
            }
        });*/
        
    }

    private class ApplicationKeyEventDispatcher implements KeyEventDispatcher {
        
        JDialog dialog;

        public ApplicationKeyEventDispatcher( JDialog dialog ) {
            this.dialog = dialog;
        }
        
        @Override
        public boolean dispatchKeyEvent( KeyEvent e ) {
                
            if ( e.getID() == KeyEvent.KEY_RELEASED ) {

                if ( e.isShiftDown() ) {

                    switch ( e.getKeyCode() ) {
                    }

                } else if ( e.isControlDown() ) {

                    switch ( e.getKeyCode() ) {
                    }

                } else if ( e.isAltDown() ) { 

                    switch ( e.getKeyCode() ) {
                    }

                } else {

                    switch ( e.getKeyCode() ) {

                        case KeyEvent.VK_ENTER:
                            accept();
                            break;

                        case KeyEvent.VK_ESCAPE:
                            cancel();
                            break;

                    }

                }

            }

            return false;
            
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        broadcastAreaSelectPanel = new br.com.davidbuzatto.basicscreenbroadcast.gui.BroadcastAreaSelectPanel();
        btnOkTR = new javax.swing.JButton();
        btnOkTL = new javax.swing.JButton();
        btnOkBL = new javax.swing.JButton();
        btnOkBR = new javax.swing.JButton();
        btnCancelTR = new javax.swing.JButton();
        btnCancelTL = new javax.swing.JButton();
        btnCancelBL = new javax.swing.JButton();
        btnCancelBR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Broadcast Area Selector");
        setUndecorated(true);

        btnOkTR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/basicscreenbroadcast/gui/icons/accept.png"))); // NOI18N
        btnOkTR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnOkTR.setOpaque(false);
        btnOkTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkTRActionPerformed(evt);
            }
        });

        btnOkTL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/basicscreenbroadcast/gui/icons/accept.png"))); // NOI18N
        btnOkTL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnOkTL.setOpaque(false);
        btnOkTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkTLActionPerformed(evt);
            }
        });

        btnOkBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/basicscreenbroadcast/gui/icons/accept.png"))); // NOI18N
        btnOkBL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnOkBL.setOpaque(false);
        btnOkBL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkBLActionPerformed(evt);
            }
        });

        btnOkBR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/basicscreenbroadcast/gui/icons/accept.png"))); // NOI18N
        btnOkBR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnOkBR.setOpaque(false);
        btnOkBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkBRActionPerformed(evt);
            }
        });

        btnCancelTR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/basicscreenbroadcast/gui/icons/cancel.png"))); // NOI18N
        btnCancelTR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelTR.setOpaque(false);
        btnCancelTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelTRActionPerformed(evt);
            }
        });

        btnCancelTL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/basicscreenbroadcast/gui/icons/cancel.png"))); // NOI18N
        btnCancelTL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelTL.setOpaque(false);
        btnCancelTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelTLActionPerformed(evt);
            }
        });

        btnCancelBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/basicscreenbroadcast/gui/icons/cancel.png"))); // NOI18N
        btnCancelBL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelBL.setOpaque(false);
        btnCancelBL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelBLActionPerformed(evt);
            }
        });

        btnCancelBR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/basicscreenbroadcast/gui/icons/cancel.png"))); // NOI18N
        btnCancelBR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelBR.setOpaque(false);
        btnCancelBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelBRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout broadcastAreaSelectPanelLayout = new javax.swing.GroupLayout(broadcastAreaSelectPanel);
        broadcastAreaSelectPanel.setLayout(broadcastAreaSelectPanelLayout);
        broadcastAreaSelectPanelLayout.setHorizontalGroup(
            broadcastAreaSelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(broadcastAreaSelectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(broadcastAreaSelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(broadcastAreaSelectPanelLayout.createSequentialGroup()
                        .addComponent(btnOkTL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelTL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                        .addComponent(btnOkTR, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelTR, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(broadcastAreaSelectPanelLayout.createSequentialGroup()
                        .addGroup(broadcastAreaSelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOkBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(broadcastAreaSelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOkBR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelBR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        broadcastAreaSelectPanelLayout.setVerticalGroup(
            broadcastAreaSelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(broadcastAreaSelectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(broadcastAreaSelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOkTL)
                    .addComponent(btnOkTR)
                    .addComponent(btnCancelTL)
                    .addComponent(btnCancelTR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addGroup(broadcastAreaSelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, broadcastAreaSelectPanelLayout.createSequentialGroup()
                        .addComponent(btnOkBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelBL))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, broadcastAreaSelectPanelLayout.createSequentialGroup()
                        .addComponent(btnOkBR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelBR)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(broadcastAreaSelectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(broadcastAreaSelectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkTLActionPerformed
        accept();
    }//GEN-LAST:event_btnOkTLActionPerformed

    private void btnOkTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkTRActionPerformed
        accept();
    }//GEN-LAST:event_btnOkTRActionPerformed

    private void btnOkBLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkBLActionPerformed
        accept();
    }//GEN-LAST:event_btnOkBLActionPerformed

    private void btnOkBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkBRActionPerformed
        accept();
    }//GEN-LAST:event_btnOkBRActionPerformed

    private void btnCancelTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelTLActionPerformed
        cancel();
    }//GEN-LAST:event_btnCancelTLActionPerformed

    private void btnCancelTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelTRActionPerformed
        cancel();
    }//GEN-LAST:event_btnCancelTRActionPerformed

    private void btnCancelBLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelBLActionPerformed
        cancel();
    }//GEN-LAST:event_btnCancelBLActionPerformed

    private void btnCancelBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelBRActionPerformed
        cancel();
    }//GEN-LAST:event_btnCancelBRActionPerformed

    private void accept() {
        
        parent.clearBroadcastAreas();
        
        for ( BroadcastArea ba : broadcastAreaSelectPanel.getSelectedBroadcastAreaList() ) {
            parent.addBroadcastArea( ba );
        }
        
        dispose();
        parent.setVisible( true );
        
    }
    
    private void cancel() {
        dispose();
        parent.setVisible( true );
    }
    
    public void addKeyEventDispatcher() {
        focusManager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
        appKeyDisp = new ApplicationKeyEventDispatcher( this );
        focusManager.addKeyEventDispatcher( appKeyDisp );
    }
    
    public void removeKeyEventDispatcher() {
        focusManager.removeKeyEventDispatcher( appKeyDisp );
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.davidbuzatto.basicscreenbroadcast.gui.BroadcastAreaSelectPanel broadcastAreaSelectPanel;
    private javax.swing.JButton btnCancelBL;
    private javax.swing.JButton btnCancelBR;
    private javax.swing.JButton btnCancelTL;
    private javax.swing.JButton btnCancelTR;
    private javax.swing.JButton btnOkBL;
    private javax.swing.JButton btnOkBR;
    private javax.swing.JButton btnOkTL;
    private javax.swing.JButton btnOkTR;
    // End of variables declaration//GEN-END:variables
}
