/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.davidbuzatto.basicscreenbroadcast.gui;

import br.com.davidbuzatto.basicscreenbroadcast.gui.model.BroadcastArea;
import java.awt.Rectangle;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author David
 */
public class MainWindow extends javax.swing.JFrame {

    private DefaultListModel<BroadcastArea> lstBroadcastAreaDefinitionsModel;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        
        initComponents();
        
        lstBroadcastAreaDefinitionsModel = new DefaultListModel<>();
        lstBroadcastAreaDefinitions.setModel( lstBroadcastAreaDefinitionsModel );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        pnlClient = new javax.swing.JPanel();
        lblClientHost = new javax.swing.JLabel();
        txtClientHost = new javax.swing.JTextField();
        lblClientPort = new javax.swing.JLabel();
        txtClientPort = new javax.swing.JTextField();
        btnClientConnect = new javax.swing.JButton();
        btnClientDisconnect = new javax.swing.JButton();
        pnlServer = new javax.swing.JPanel();
        lblServerPort = new javax.swing.JLabel();
        txtServerPort = new javax.swing.JTextField();
        lblFPSGeneration = new javax.swing.JLabel();
        txtFPSGeneration = new javax.swing.JTextField();
        pnlScreenAreas = new javax.swing.JPanel();
        radioFullScreen = new javax.swing.JRadioButton();
        radioCustomizedBroadscastAreas = new javax.swing.JRadioButton();
        pnlBroascastAreaDefinitions = new javax.swing.JPanel();
        sclBroadcastAreaDefinitions = new javax.swing.JScrollPane();
        lstBroadcastAreaDefinitions = new javax.swing.JList<>();
        btnEditBroadcastAreas = new javax.swing.JButton();
        btnSaveBroadcastAreas = new javax.swing.JButton();
        btnLoadBroadcastAreas = new javax.swing.JButton();
        btnServerStart = new javax.swing.JButton();
        btnServerStop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Basic Screen Broadcast - By David Buzatto");
        setResizable(false);

        pnlClient.setBorder(javax.swing.BorderFactory.createTitledBorder("Client Configurations"));
        pnlClient.setToolTipText("");

        lblClientHost.setText("Host:");

        txtClientHost.setText("localhost");

        lblClientPort.setText("Port:");

        txtClientPort.setText("8085");

        btnClientConnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/basicscreenbroadcast/gui/icons/connect.png"))); // NOI18N
        btnClientConnect.setMnemonic('C');
        btnClientConnect.setText("Connect");
        btnClientConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientConnectActionPerformed(evt);
            }
        });

        btnClientDisconnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/basicscreenbroadcast/gui/icons/disconnect.png"))); // NOI18N
        btnClientDisconnect.setMnemonic('D');
        btnClientDisconnect.setText("Disconnect");
        btnClientDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientDisconnectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlClientLayout = new javax.swing.GroupLayout(pnlClient);
        pnlClient.setLayout(pnlClientLayout);
        pnlClientLayout.setHorizontalGroup(
            pnlClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClientHost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClientHost, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClientPort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClientPort, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClientConnect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClientDisconnect)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pnlClientLayout.setVerticalGroup(
            pnlClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClientHost)
                    .addComponent(txtClientHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClientPort)
                    .addComponent(txtClientPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClientConnect)
                    .addComponent(btnClientDisconnect))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlServer.setBorder(javax.swing.BorderFactory.createTitledBorder("Server Configurations"));

        lblServerPort.setText("Port:");

        txtServerPort.setText("8085");

        lblFPSGeneration.setText("FPS Generation:");

        txtFPSGeneration.setText("30");

        pnlScreenAreas.setBorder(javax.swing.BorderFactory.createTitledBorder("Screen Areas to Broadcast"));

        btnGroup.add(radioFullScreen);
        radioFullScreen.setSelected(true);
        radioFullScreen.setText("Full Screen");
        radioFullScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFullScreenActionPerformed(evt);
            }
        });

        btnGroup.add(radioCustomizedBroadscastAreas);
        radioCustomizedBroadscastAreas.setText("Customized Broadcast Areas");
        radioCustomizedBroadscastAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCustomizedBroadscastAreasActionPerformed(evt);
            }
        });

        pnlBroascastAreaDefinitions.setBorder(javax.swing.BorderFactory.createTitledBorder("Broadcast Area Definitions"));

        lstBroadcastAreaDefinitions.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstBroadcastAreaDefinitions.setEnabled(false);
        sclBroadcastAreaDefinitions.setViewportView(lstBroadcastAreaDefinitions);

        btnEditBroadcastAreas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/basicscreenbroadcast/gui/icons/pencil.png"))); // NOI18N
        btnEditBroadcastAreas.setMnemonic('E');
        btnEditBroadcastAreas.setText("Edit");
        btnEditBroadcastAreas.setEnabled(false);
        btnEditBroadcastAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBroadcastAreasActionPerformed(evt);
            }
        });

        btnSaveBroadcastAreas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/basicscreenbroadcast/gui/icons/disk.png"))); // NOI18N
        btnSaveBroadcastAreas.setMnemonic('S');
        btnSaveBroadcastAreas.setText("Save");
        btnSaveBroadcastAreas.setEnabled(false);
        btnSaveBroadcastAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveBroadcastAreasActionPerformed(evt);
            }
        });

        btnLoadBroadcastAreas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/basicscreenbroadcast/gui/icons/folder_wrench.png"))); // NOI18N
        btnLoadBroadcastAreas.setMnemonic('L');
        btnLoadBroadcastAreas.setText("Load");
        btnLoadBroadcastAreas.setEnabled(false);
        btnLoadBroadcastAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadBroadcastAreasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBroascastAreaDefinitionsLayout = new javax.swing.GroupLayout(pnlBroascastAreaDefinitions);
        pnlBroascastAreaDefinitions.setLayout(pnlBroascastAreaDefinitionsLayout);
        pnlBroascastAreaDefinitionsLayout.setHorizontalGroup(
            pnlBroascastAreaDefinitionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBroascastAreaDefinitionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBroascastAreaDefinitionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sclBroadcastAreaDefinitions)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBroascastAreaDefinitionsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEditBroadcastAreas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLoadBroadcastAreas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaveBroadcastAreas)))
                .addContainerGap())
        );
        pnlBroascastAreaDefinitionsLayout.setVerticalGroup(
            pnlBroascastAreaDefinitionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBroascastAreaDefinitionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sclBroadcastAreaDefinitions, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBroascastAreaDefinitionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditBroadcastAreas)
                    .addComponent(btnSaveBroadcastAreas)
                    .addComponent(btnLoadBroadcastAreas))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlScreenAreasLayout = new javax.swing.GroupLayout(pnlScreenAreas);
        pnlScreenAreas.setLayout(pnlScreenAreasLayout);
        pnlScreenAreasLayout.setHorizontalGroup(
            pnlScreenAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScreenAreasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlScreenAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBroascastAreaDefinitions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlScreenAreasLayout.createSequentialGroup()
                        .addComponent(radioFullScreen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioCustomizedBroadscastAreas)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlScreenAreasLayout.setVerticalGroup(
            pnlScreenAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScreenAreasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlScreenAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioFullScreen)
                    .addComponent(radioCustomizedBroadscastAreas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBroascastAreaDefinitions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnServerStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/basicscreenbroadcast/gui/icons/transmit_go.png"))); // NOI18N
        btnServerStart.setMnemonic('a');
        btnServerStart.setText("Start");
        btnServerStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServerStartActionPerformed(evt);
            }
        });

        btnServerStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/basicscreenbroadcast/gui/icons/transmit_delete.png"))); // NOI18N
        btnServerStop.setMnemonic('o');
        btnServerStop.setText("Stop");
        btnServerStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServerStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlServerLayout = new javax.swing.GroupLayout(pnlServer);
        pnlServer.setLayout(pnlServerLayout);
        pnlServerLayout.setHorizontalGroup(
            pnlServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlScreenAreas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlServerLayout.createSequentialGroup()
                        .addComponent(lblServerPort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFPSGeneration)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFPSGeneration, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnServerStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnServerStop)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlServerLayout.setVerticalGroup(
            pnlServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServerPort)
                    .addComponent(txtServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFPSGeneration)
                    .addComponent(txtFPSGeneration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnServerStart)
                    .addComponent(btnServerStop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlScreenAreas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientConnectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClientConnectActionPerformed

    private void btnClientDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientDisconnectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClientDisconnectActionPerformed

    private void btnServerStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServerStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnServerStartActionPerformed

    private void btnServerStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServerStopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnServerStopActionPerformed

    private void radioFullScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFullScreenActionPerformed
        lstBroadcastAreaDefinitions.setEnabled( false );
        btnEditBroadcastAreas.setEnabled( false );
        btnLoadBroadcastAreas.setEnabled( false );
        btnSaveBroadcastAreas.setEnabled( false );
    }//GEN-LAST:event_radioFullScreenActionPerformed

    private void radioCustomizedBroadscastAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCustomizedBroadscastAreasActionPerformed
        lstBroadcastAreaDefinitions.setEnabled( true );
        btnEditBroadcastAreas.setEnabled( true );
        btnLoadBroadcastAreas.setEnabled( true );
        btnSaveBroadcastAreas.setEnabled( true );
    }//GEN-LAST:event_radioCustomizedBroadscastAreasActionPerformed

    private void btnEditBroadcastAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBroadcastAreasActionPerformed
        
        setVisible( false );
        
        BroadcastAreaSelectDialog d = new BroadcastAreaSelectDialog( this, true );
        d.setVisible( true );
        
    }//GEN-LAST:event_btnEditBroadcastAreasActionPerformed

    private void btnLoadBroadcastAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadBroadcastAreasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoadBroadcastAreasActionPerformed

    private void btnSaveBroadcastAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveBroadcastAreasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveBroadcastAreasActionPerformed

    public void addBroadcastArea( BroadcastArea area ) {
        lstBroadcastAreaDefinitionsModel.addElement( area );
    }
    
    public List<BroadcastArea> getBroadcastAreas() {
        
        List<BroadcastArea> areas = new ArrayList<>();
        
        for ( int i = 0; i < lstBroadcastAreaDefinitionsModel.size(); i++ ) {
            areas.add( lstBroadcastAreaDefinitionsModel.get( i ) );
        }
        
        return areas;
        
    }
    
    public void clearBroadcastAreas() {
        lstBroadcastAreaDefinitionsModel.clear();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() ) {
                if ( "Nimbus".equals( info.getName() ) ) {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        } catch ( ClassNotFoundException ex ) {
            java.util.logging.Logger.getLogger( MainWindow.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( InstantiationException ex ) {
            java.util.logging.Logger.getLogger( MainWindow.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( IllegalAccessException ex ) {
            java.util.logging.Logger.getLogger( MainWindow.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( javax.swing.UnsupportedLookAndFeelException ex ) {
            java.util.logging.Logger.getLogger( MainWindow.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable() {
            public void run() {
                new MainWindow().setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientConnect;
    private javax.swing.JButton btnClientDisconnect;
    private javax.swing.JButton btnEditBroadcastAreas;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnLoadBroadcastAreas;
    private javax.swing.JButton btnSaveBroadcastAreas;
    private javax.swing.JButton btnServerStart;
    private javax.swing.JButton btnServerStop;
    private javax.swing.JLabel lblClientHost;
    private javax.swing.JLabel lblClientPort;
    private javax.swing.JLabel lblFPSGeneration;
    private javax.swing.JLabel lblServerPort;
    private javax.swing.JList<BroadcastArea> lstBroadcastAreaDefinitions;
    private javax.swing.JPanel pnlBroascastAreaDefinitions;
    private javax.swing.JPanel pnlClient;
    private javax.swing.JPanel pnlScreenAreas;
    private javax.swing.JPanel pnlServer;
    private javax.swing.JRadioButton radioCustomizedBroadscastAreas;
    private javax.swing.JRadioButton radioFullScreen;
    private javax.swing.JScrollPane sclBroadcastAreaDefinitions;
    private javax.swing.JTextField txtClientHost;
    private javax.swing.JTextField txtClientPort;
    private javax.swing.JTextField txtFPSGeneration;
    private javax.swing.JTextField txtServerPort;
    // End of variables declaration//GEN-END:variables
}
